### ISSUE TITLE
Mysterious mouse click (release) timeout.

### ISSUE THREAD

**Issue by alex-rsk** [chrome-php/headless-chromium-php#141]
I have headless chrome application. It is running on my home computer very well. It opens some page, makes mouse click and presses "Space" in text input field.

But when it was uploaded to VDS, it throws mouse timeout on 3 sec, while doing mouse release. 
   Stack trace:

``
#0 /var/www/myapp/vendor/chrome-php/chrome/src/Communication/ResponseReader.php(103): HeadlessChromium\Utils::tryWithTimeout(3000000, Object(Generator))
#1 /var/www/myapp/vendor/chrome-php/chrome/src/Communication/Session.php(79): HeadlessChromium\Communication\ResponseReader->waitForResponse(3000)
#2 /var/www/myapp/vendor/chrome-php/chrome/src/Input/Mouse.php(168): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#3 /var/www/myapp/vendor/chrome-php/chrome/src/Input/Mouse.php(182): HeadlessChromium\Input\Mouse->release(NULL)
#4 /var/www/myapp/app/Components/GHC/GHCBrowser.php(321): HeadlessChromium\Input\Mouse->click()
``

But according to debug logs, the response to release event comes immediately:

[2020-03-27 00:41:34] DEBUG socket(2): в†’ sending data:{"id":27,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":26,\"method\":\"Input.dispatchMouseEvent\",\"params\":
{\"x\":273,\"y\":324,\"type\":\"mouseReleased\",\"button\":\"left\",\"clickCount\":1}}","sessionId":"E9CCECFCBA3B2659FF3637AB69038097"}}
[2020-03-27 00:41:34] DEBUG socket(2): в†ђ receiving data:{"id":27,"result":{}}

Where is the problem rooted?
I tried:

*  setViewport(1280,1000) after page opening
*  Added key --window-size to command line

 and no gain

Command line
``
'/usr/bin/google-chrome' 
'--remote-debugging-port=0'
 '--disable-background-networking'
 '--disable-background-timer-throttling'
'--disable-client-side-phishing-detection' 
'--disable-default-apps'
'--disable-extensions'
'--disable-hang-monitor' 
'--disable-popup-blocking'
'--disable-prompt-on-repost'
'--disable-sync'
'--disable-translate'
'--metrics-recording-only'
'--no-first-run'
'--safebrowsing-disable-auto-update'
'--enable-automation'
'--password-store=basic'
'--use-mock-keychain'
'--headless'
 '--disable-gpu'
'--hide-scrollbars'
'--mute-audio'
'--remote-debugging-port = 9224'
'--user-agent = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"'
 '--mute-audio'
'--disable-notifications'
'--disable-gpu'
'--homedir = /var/www/myapp/public/../app/Data/chrome/userData/adlibparser'
'--window-size=1280,1000' 
'--user-data-dir=/var/www/myapp/public/../app/Data/chrome/userData/adlibparser'
``

[Debug log](https://gist.github.com/alex-rsk/26a2120df95302156b5a3fc95567dd1f)

I'm lack of ideas. 
Any help would be very appreciated!

**Comment by alex-rsk** [comment]
UPD
The problem still presents, and gone, simultaneously
Exceptions from mouse keep going, but they don’t influence to browser actions!
I.e., the mouse click successfully happens, but the lib throws an exception.
I just caught the exception and continue to work further.
But the problem seem to be existing, and only on VDS.
