### ISSUE TITLE
Running as root without --no-sandbox is not supported.

### ISSUE THREAD

**Issue by seitymoe** [chrome-php/headless-chromium-php#144]
When I try to create a new browser I sometimes get this error.
The browser is created the same way, however sometimes it works and sometimes doesn't.
I'm using chrome-php version 0.8.1.
What could be the problem? Is there any way to solve this issue?

ERROR Message
```
Chrome process stopped before startup completed. Additional info: [0330/031413.464502:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180. {"exception":"[object] (RuntimeException(code: 0): Chrome process stopped before startup completed. Additional info: [0330/031413.464502:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180. at /var/www/laravel/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:379)
[stacktrace]
#0 /var/www/laravel/vendor/chrome-php/chrome/src/Utils.php(51): HeadlessChromium\\Browser\\BrowserProcess->HeadlessChromium\\Browser\\{closure}(Object(Symfony\\Component\\Process\\Process))
#1 /var/www/laravel/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(414): HeadlessChromium\\Utils::tryWithTimeout(30000000, Object(Generator))
#2 /var/www/laravel/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(128): HeadlessChromium\\Browser\\BrowserProcess->waitForStartup(Object(Symfony\\Component\\Process\\Process), 30000000)
#3 /var/www/laravel/vendor/chrome-php/chrome/src/BrowserFactory.php(78): HeadlessChromium\\Browser\\BrowserProcess->start('chromium-browse...', Array)
#4 /var/www/laravel/app/Helper/PageScanner.php(83): HeadlessChromium\\BrowserFactory->createBrowser(Array)
```

Code
```$factory = new BrowserFactory('chromium-browser');
            $this->chrome_client = $factory->createBrowser([
                'keepAlive' => true,
                'userDataDir' => $this->cookie_dir,
                'userAgent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36',
            ]);
```

**Comment by imTigger** [comment]
The problem is exactly "Running as root without --no-sandbox is not supported."
```
$browser = $browserFactory->createBrowser([
    'noSandbox' => true
]);
```

**Comment by seitymoe** [comment]
the error is gone now. Thank you!
