### ISSUE TITLE
timed out in getHtml();

### ISSUE THREAD

**Issue by ShamanHead** [chrome-php/headless-chromium-php#213]
Hi everyone, I had this error recently. How to fix that?
I have the latest version of chromium.

```
Operation timed out (2sec) in /home/shamanhead/dev/test/vendor/chrome-php/chrome/src/Utils.php:69
Stack trace:
#0 /home/shamanhead/dev/test/vendor/chrome-php/chrome/src/Communication/ResponseReader.php(108): HeadlessChromium\Utils::tryWithTimeout()
#1 /home/shamanhead/dev/test/vendor/chrome-php/chrome/src/PageUtils/PageEvaluation.php(74): HeadlessChromium\Communication\ResponseReader->waitForResponse()
#2 /home/shamanhead/dev/test/vendor/chrome-php/chrome/src/PageUtils/PageEvaluation.php(106): HeadlessChromium\PageUtils\PageEvaluation->waitForResponse()
#3 /home/shamanhead/dev/test/vendor/chrome-php/chrome/src/Page.php(819): HeadlessChromium\PageUtils\PageEvaluation->getReturnValue()
#4 /home/shamanhead/dev/test/ind.php(238): HeadlessChromium\Page->getHtml()
#5 {main}
  thrown in /home/shamanhead/dev/test/vendor/chrome-php/chrome/src/Utils.php on line 69
```

**Comment by maximgrynykha** [comment]
@ShamanHead please give a look at your environment (list it in the next way - [OS | Web Server | version of PHP]) and put the code example that you used to receive this issue.

**Comment by ShamanHead** [comment]
@ismaxim That problem occurs when script tryin' to get html ~1 time in second, so the chrome can't process so many requests. Helpful tip can be just increase process wait timer.
