### ISSUE TITLE
[BUG] Unexpected exception when sending Close frame

### ISSUE THREAD

**Issue by gdplayerto** [chrome-php/headless-chromium-php#348]
OS: Windows 10
PHP: 7.3.25
Chome: 98.0.4758.102 (Official Build) (64-bit)

I always get error message like this "**Unexpected exception when sending Close frame**"

```
[26-Feb-2022 12:34:54 UTC] PHP Fatal error:  Uncaught Wrench\Exception\FrameException: Unexpected exception when sending Close frame. in D:\laragon\www\gdplayer\vendor\chrome-php\wrench\src\Client.php:264
Stack trace:
#0 D:\laragon\www\gdplayer\vendor\chrome-php\chrome\src\Communication\Socket\Wrench.php(128): Wrench\Client->disconnect(1000)
#1 D:\laragon\www\gdplayer\vendor\chrome-php\chrome\src\Communication\Connection.php(196): HeadlessChromium\Communication\Socket\Wrench->disconnect()
#2 D:\laragon\www\gdplayer\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(226): HeadlessChromium\Communication\Connection->disconnect()
#3 D:\laragon\www\gdplayer\vendor\chrome-php\chrome\src\Browser\ProcessAwareBrowser.php(36): HeadlessChromium\Browser\BrowserProcess->kill()
#4 D:\laragon\www\gdplayer\includes\functions.php(106): HeadlessChromium\Browser\ProcessAwareBrowser->close()
#5 D:\laragon\www\gdplayer\includes\hosting\web.class.php(159): execHeadlessChromium('https://www.web...', 'test~Rameev...')
#6 D:\laragon\www\gdplayer\includes\classes\C in D:\laragon\www\gdplayer\vendor\chrome-php\wrench\src\Client.php on line 264
```

The code I have

```
function execHeadlessChromium($url, $logName)
{
    session_write_close();

    create_dir(BASE_DIR . 'cache');
    create_dir(BASE_DIR . 'cache/logs');

    $logFile = BASE_DIR . 'cache/logs/' . $logName . '.log';
    $logConfig = [];

    if (file_exists($logFile)) unlink($logFile);

    try {
        $chromeInstance = PHP_OS_FAMILY === 'Windows' ? null : 'google-chrome';
        $browserFactory = new \HeadlessChromium\BrowserFactory($chromeInstance);
        $browser = $browserFactory->createBrowser($logConfig);

        $page = $browser->createPage();
        $page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message('Network.setExtraHTTPHeaders', [
            'headers' => [
                'Accept-Language' => 'id,en;q=0.9,id-ID;q=0.8',
                'User-Agent' => USER_AGENT
            ]
        ]));
        $page->navigate($url)->waitForNavigation(\HeadlessChromium\Page::DOM_CONTENT_LOADED, 3000000);
        $content = $page->getHtml(3000000);

        $fp = fopen($logFile, 'a+');
        stream_set_blocking($fp, false);
        if (flock($fp, LOCK_EX)) {
            fwrite($fp, $content, strlen($content));
            fflush($fp);
            flock($fp, LOCK_UN);
        }
        fclose($fp);
        return $logFile;
    } catch (\HeadlessChromium\Exception\OperationTimedOut | \HeadlessChromium\Exception\NavigationExpired | \Wrench\Exception\FrameException | \Exception $e) {
        error_log('execHeadlessChromium => ' . $e->getMessage());
        $browser->close();
        return $logFile;
    } finally {
        $browser->close();
        return $logFile;
    }
    return $logFile;
}
echo execHeadlessChromium('http://test.com', 'testLog');
```
The log file was created successfully but the error was caught as I mentioned

**Comment by enricodias** [comment]
Isn't that caused by you trying to call `::close()` twice? The `finally` block will always be executed, so if you catch an exception in that `catch` block, it will execute the close method inside the `catch` and then again inside the `finally` block.

**Comment by gdplayerto** [comment]
Yes, `::close()` no longer needed on `catch` or `finally`
