### ISSUE TITLE
Operation timed out after 2.

### ISSUE THREAD

**Issue by codewizdevs** [chrome-php/headless-chromium-php#353]
Hi, 

I have problem:

```
Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 2s. in C:\xampp\htdocs\kuponi\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Stack trace:
#0 C:\xampp\htdocs\kuponi\vendor\chrome-php\chrome\src\Utils.php(64): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(2000000)
#1 C:\xampp\htdocs\kuponi\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(115): HeadlessChromium\Utils::tryWithTimeout(2000000, Object(Generator))
#2 C:\xampp\htdocs\kuponi\vendor\chrome-php\chrome\src\PageUtils\PageEvaluation.php(77): HeadlessChromium\Communication\ResponseReader->waitForResponse(2000)
#3 C:\xampp\htdocs\kuponi\vendor\chrome-php\chrome\src\PageUtils\PageEvaluation.php(107): HeadlessChromium\PageUtils\PageEvaluation->waitForResponse(NULL)
#4 C:\xampp\htdocs\kuponi\vendor\chrome-php\chrome\src\Page.php(817): HeadlessChromium\PageUtils\PageEvaluation->getReturnValue(NULL)
#5 C:\xampp\htdocs\kuponi\test.php(18): HeadlessChromium\Page->getHtml()
#6 {main}
  thrown in C:\xampp\htdocs\kuponi\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php on line 18
```

```
    $page = $browser->createPage();
    $page->navigate('https://www.audreylanglois-paris.fr')->waitForNavigation();

 
    $html = $page->getHtml();

    echo $html;
```

If i use  https://google.com it works fine, for some sites it just has this error, can you clarify why this happens? Regards

**Comment by enricodias** [comment]
Like the exception explains, a timeout happened. Increase the timeout value in the `getHtml` method.

**Comment by codewizdevs** [comment]
@enricodias 

When i set headless to false, the browser opens and page loads fine, after few seconds method fails. Happens on evaluate title as well, how do i set timeout?

Regards

**Comment by enricodias** [comment]
```php
$html = $page->getHtml(10000); // timeout in milliseconds
```

**Comment by Muzaffar-Shoshiy** [comment]
sexy

**Comment by oldravian** [comment]
2024: I'm still facing this issue
how to mention timeout values in my case?

```
            $page = $browser->createPage();
            $page->setHtml($html);

            // Take a screenshot
            $screenshot = $page->screenshot();
            // Get base64 data of the screenshot
            $base64 = $screenshot->getBase64();
            return 'data:image/png;base64,' . $base64;
```

**Comment by mihirpatel1112** [comment]
![Image](https://github.com/user-attachments/assets/61ed3f77-a730-44eb-9dd7-95e878466b94)
