### ISSUE TITLE
Chrome process stopped before startup completed (When headless is false)

### ISSUE THREAD

**Issue by foremtehan** [chrome-php/headless-chromium-php#355]
I want to use my real chrome browser in my windows but the following error occurs :

Version 99.0.4844.74 (Official Build) (64-bit)
chrome-php/chrome v1.4.0

```php
$browserFactory = new BrowserFactory("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe");

$browser = $browserFactory->createBrowser([
    'headless' => false,
    'userDataDir' => 'C:\Users\AppData\Local\Google\Chrome\User Data',
]);

$page = $browser->createPage();
$page->navigate('https://example.com')->waitForNavigation();
```

```
Chrome process stopped before startup completed.#0 vendor\chrome-php\chrome\src\Utils.php(57): HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process))
#1 vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(446): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator))
#2 vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(139): HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object(Symfony\Component\Process\Process), 30000000)
#3 vendor\chrome-php\chrome\src\BrowserFactory.php(81): HeadlessChromium\Browser\BrowserProcess->start('C:\\Program File...', Array)
#4 app\Console\Commands\Browse.php(26): HeadlessChromium\BrowserFactory->createBrowser(Array)
#5 vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\BrowseSubscene->handle()
#6 vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#8 vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#9 vendor\laravel\framework\src\Illuminate\Container\Container.php(653): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#10 vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call(Array)
#11 vendor\symfony\console\Command\Command.php(291): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#12 vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 vendor\symfony\console\Application.php(989): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\BrowseSubscene), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 vendor\laravel\framework\src\Illuminate\Console\Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main}
```

**Comment by foremtehan** [comment]
my user data path was invalid
