### ISSUE TITLE
How to prevent timeout on big file

### ISSUE THREAD

**Issue by yuseferi** [chrome-php/headless-chromium-php#381]
I have the following code.
it's trying to generate PDF version of a large page.
the chrome headless is not in my machine and I call it but still in the same network.

this is my could

```
$autoloader = require_once 'web/autoload.php';

use HeadlessChromium\Communication\Connection;
use HeadlessChromium\Browser;
use HeadlessChromium\Page;

// chrome devtools URI
$webSocketUri = 'ws://127.0.0.1:30000/devtools/browser/3e9b6d50-1d17-4157-ac0e-d6c6af7272ed"';

// create a connection
$connection = new Connection($webSocketUri,null, 30000);
$connection->connect();

// create browser
$browser = new Browser($connection);

try {
  // creates a new page and navigate to an URL
  $page = $browser->createPage();
  $page->navigate('https://master-7rqtwti-wnjvz3rv66pcy.eu-5.platformsh.site/en/book-page/339/en?no_lang')->waitForNavigation(Page::LOAD, 900000);

  // get page title
  $pageTitle = $page->evaluate('document.title')->getReturnValue();

  // pdf
  $page->pdf(['printBackground' => false])->saveToFile('./guideline1.pdf');
} finally {
  // bye
  $browser->close();
}
```

this is the error

```
HeadlessChromium\Communication\Message {#41
  #id: 11
  #method: "Browser.close"
  #params: []
  #sessionId: null
}
false
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 1800s. in /Users//vendor/chrome-php/chrome/src/Exception/OperationTimedOut.php:18
Stack trace:
#0 /Users//vendor/chrome-php/chrome/src/Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(1800000000)
#1 /Users//vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php(132): HeadlessChromium\Utils::tryWithTimeout(1800000000, Object(Generator))
#2 /Users//_db/test.php(22): HeadlessChromium\PageUtils\PageNavigation->waitForNavigation('load', 1800000)
#3 {main}

Next HeadlessChromium\Exception\CommunicationException: Message could not be sent. Reason: the connection is closed. in /Users//vendor/chrome-php/chrome/src/Communication/Connection.php:254
Stack trace:
#0 /Users//vendor/chrome-php/chrome/src/Communication/Connection.php(270): HeadlessChromium\Communication\Connection->sendMessage('Message could n...')
#1 /Users//vendor/chrome-php/chrome/src/Browser.php(127): HeadlessChromium\Communication\Connection->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#2 /Users//vendor/chrome-php/chrome/src/Browser.php(117): HeadlessChromium\Browser->sendCloseMessage()
#3 /Users//_db/test.php(31): HeadlessChromium\Browser->close()
#4 {main}
  thrown in /Users//vendor/chrome-php/chrome/src/Communication/Connection.php on line 254

Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 1800s. in /Users//vendor/chrome-php/chrome/src/Exception/OperationTimedOut.php:18
Stack trace:
#0 /Users//vendor/chrome-php/chrome/src/Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(1800000000)
#1 /Users//vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php(132): HeadlessChromium\Utils::tryWithTimeout(1800000000, Object(Generator))
#2 /Users//_db/test.php(22): HeadlessChromium\PageUtils\PageNavigation->waitForNavigation('load', 1800000)
#3 {main}

Next HeadlessChromium\Exception\CommunicationException: Message could not be sent. Reason: the connection is closed. in /Users//vendor/chrome-php/chrome/src/Communication/Connection.php:254
Stack trace:
#0 /Users//vendor/chrome-php/chrome/src/Communication/Connection.php(270): HeadlessChromium\Communication\Connection->sendMessage('Message could n...')
#1 /Users//vendor/chrome-php/chrome/src/Browser.php(127): HeadlessChromium\Communication\Connection->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#2 /Users//vendor/chrome-php/chrome/src/Browser.php(117): HeadlessChromium\Browser->sendCloseMessage()
#3 /Users//_db/test.php(31): HeadlessChromium\Browser->close()
#4 {main}
  thrown in /Users//vendor/chrome-php/chrome/src/Communication/Connection.php on line 254

```

I'm wondering how can I achieve this without a timeout error?

**Comment by enricodias** [comment]
In which part of your code the timeout occurs? Right in the navigation?

**Comment by yuseferi** [comment]
Hi @enricodias, thanks for your attention. in Saving PDF. 
I fixed navigation part by adding more cache in our side.
as you can see the pages I want to generate pdf are  pretty big for sample: 

https://master-7rqtwti-wnjvz3rv66pcy.eu-5.platformsh.site/en/msf_pdf/book/339?no_lang

any adivces?  at the mement I set timeout to  `1500000`  but still it failed.

```
          $page->pdf(['printBackground' => FALSE])
            ->saveToFile('sites/default/files/pdf/' . $title . '.pdf', 1500000);
```

**Comment by enricodias** [comment]
I saw your last reply but I couldn't think in a way to mitigate this. Chrome will only send the pdf after finish creating it.
