### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed

### ISSUE THREAD

**Issue by PSPVOLT** [chrome-php/headless-chromium-php#391]
Hello.

I have this error: 

Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted in /var/www/site/data/www/site.ru/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:400 Stack trace: #0 /var/www/site/data/www/site.ru/vendor/chrome-php/chrome/src/Utils.php(57): HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process)) #1/var/www/site/data/www/site.ru/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(437): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator)) #2 /var/www/site/data/www/site.ru/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(139): HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object(Symfony\Component\Process\Process), 30000000) #3 /var/www/api-kino/data/www/torrent.api-kino.ru/vendor/chrom in /var/www/site/data/www/site.ru/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php on line 400 

I use Linux, PHP 7.4 + php-fpm nginx

Please tell me how to solve this problem on AlmaLinux server

Thanks in advance for your reply.

```
@ini_set ( 'display_errors', true );
@ini_set ( 'html_errors', false );

require __DIR__ . '/vendor/autoload.php';

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory('google-chrome');


$browser = $browserFactory->createBrowser();

try {

    $page = $browser->createPage();
    $page->navigate('https://site.ru')->waitForNavigation();


    $pageTitle = $page->evaluate('document.title')->getReturnValue();


    $page->screenshot()->saveToFile('bar.png');


    $page->pdf(['printBackground' => false])->saveToFile('bar.pdf');
} finally {

    $browser->close();
}
```

**Comment by PSPVOLT** [comment]
Found a solution

```
$browser = $browserFactory->createBrowser([
    'noSandbox' => true, // Enable no sandbox mode, useful to run in a docker container
]);
```
