### ISSUE TITLE
Error:  Operation timed out after 60s. for BrowserFactory for Ubuntu 20.04 [FIXED]

### ISSUE THREAD

**Issue by DenisSokoloff** [chrome-php/headless-chromium-php#394]
Works great for months, but now, got error, I update chromium only, but did not check, have found error now

Ubuntu 20.04
Google Chrome 103.0.5060.53
Chrome-php 1.6.0 (Updated to 1.6.1)

`$browserFactory = new \HeadlessChromium\BrowserFactory("google-chrome");
`

<b>Fatal error</b>:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 60s. in /vendor/chrome-php/chrome/src/Exception/OperationTimedOut.php:18
--
  | Stack trace:
  | #0 /vendor/chrome-php/chrome/src/Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(60000000)
  | #1 /vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(447): HeadlessChromium\Utils::tryWithTimeout(60000000, Object(Generator))
  | #2 /vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(139): HeadlessChromium\Browser\BrowserProcess-&gt;waitForStartup(Object(Symfony\Component\Process\Process), 60000000)
  | #3 /vendor/chrome-php/chrome/src/BrowserFactory.php(81): HeadlessChromium\Browser\BrowserProcess-&gt;start('google-chrome', Array)
  | #4  in <b>/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php</b> on line <b>449</b><br />

Debug:

```
[2022-07-02T13:19:41.361769+02:00] chrome.DEBUG: process: initializing [] []
[2022-07-02T13:19:41.362060+02:00] chrome.DEBUG: process: using directory: /tmp/chromium-php-uRdX68 [] []
[2022-07-02T13:19:41.362146+02:00] chrome.DEBUG: process: starting process: 'google-chrome' '--remote-debugging-port=0' '--disable-background-networking' '--disable-background-timer-throttling' '--disable-client-side-phishing-detection' '--disable-hang-monitor' '--disable-popup-blocking' '--disable-prompt-on-repost' '--disable-sync' '--disable-translate' '--disable-features=ChromeWhatsNewUI' '--metrics-recording-only' '--no-first-run' '--safebrowsing-disable-auto-update' '--enable-automation' '--password-store=basic' '--use-mock-keychain' '--window-size=1366,768' '--no-sandbox' '--ignore-certificate-errors' '--user-data-dir=/tmp/chromium-php-uRdX68' [] []
[2022-07-02T13:19:41.363814+02:00] chrome.DEBUG: process: waiting for 60 seconds for startup [] []
[2022-07-02T13:19:41.394424+02:00] chrome.DEBUG: process: chrome output:chrome_crashpad_handler: --database is required Try 'chrome_crashpad_handler --help' for more information. [] []
[2022-07-02T13:19:41.394484+02:00] chrome.DEBUG: process: ignoring output:chrome_crashpad_handler: --database is required [] []
[2022-07-02T13:19:41.394503+02:00] chrome.DEBUG: process: ignoring output:Try 'chrome_crashpad_handler --help' for more information. [] []
[2022-07-02T13:20:41.358634+02:00] chrome.DEBUG: process: killing chrome [] []
[2022-07-02T13:20:41.358710+02:00] chrome.DEBUG: process: stopping process [] []
[2022-07-02T13:20:41.360976+02:00] chrome.DEBUG: process: process stopped with exit code 143 [] []
[2022-07-02T13:20:41.361023+02:00] chrome.DEBUG: process: cleaning temporary resources:/tmp/chromium-php-uRdX68 [] []

```

**chrome.DEBUG: process: chrome output:chrome_crashpad_handler: --database is required Try 'chrome_crashpad_handler --help' for more information.**

What is mean?

**Comment by DenisSokoloff** [comment]
- /tmp/Crashpad
- /tmp/Crashpad/new
- /tmp/Crashpad/settings.dat

Fixed by changing permission to 0777 for above folders

**Comment by DenysSokolovBack** [comment]
My main account @DenisSokoloff  was blocked for comments; I don't know why. @enricodias ?



For Google Chrome: 128.0.6613.119
Ubuntu: 24.04

Works for me
```
sudo mkdir -p /var/www/.config/google-chrome/Crashpad
sudo chown -R www-data:www-data /var/www/.config

```

**Comment by enricodias** [comment]
@DenysSokolovBack I have no idea, I didn't even know it was possible to block someone like that. I also didn't find anything related to it in the repo settings 🤔
