### ISSUE TITLE
How to increase timeout in `Page::dom()`

### ISSUE THREAD

**Issue by Israrminhas1** [chrome-php/headless-chromium-php#395]
I get operation timeout error 
is there anyway i can increase time it takes to load dom.

**Comment by enricodias** [comment]
You get timeout doing what, exactly? There are several methods with a timeout argument.

**Comment by saltymermaidh1** [comment]
@enricodias Sorry for the noise, but I believe @Israrminhas1 is getting a timeout when trying to load the page DOM like so `$page->dom()`. I am also facing this issue when loading the DOM for large pages.

Partial stack trace:
```
Tue, 27 Sep 2022 02:44:37 +0000 HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 1000ms. in c:\path\to\project\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Tue, 27 Sep 2022 02:44:37 +0000 Stack trace:
Tue, 27 Sep 2022 02:44:37 +0000 #0 c:\path\to\project\vendor\chrome-php\chrome\src\Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(1000000)
Tue, 27 Sep 2022 02:44:37 +0000 #1 c:\path\to\project\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(115): HeadlessChromium\Utils::tryWithTimeout(1000000, Object(Generator))
Tue, 27 Sep 2022 02:44:37 +0000 #2 c:\path\to\project\vendor\chrome-php\chrome\src\Dom\Dom.php(16): HeadlessChromium\Communication\ResponseReader->waitForResponse(1000)
Tue, 27 Sep 2022 02:44:37 +0000 #3 c:\path\to\project\vendor\chrome-php\chrome\src\Page.php(774): HeadlessChromium\Dom\Dom->__construct(Object(HeadlessChromium\Page))
Tue, 27 Sep 2022 02:44:37 +0000 #4 c:\path\to\project\src\Web\Crawling\Crawler.php(108): HeadlessChromium\Page->dom()
...
```

I'm using chrome-php within a homemade web crawler for bug bounty recon.

So, in short, is there a way to increase the `$page->dom()` timeout? 

Thanks

**Comment by enricodias** [comment]
The constructor in the `Dom` class has indeed a hard coded timeout of just one second. I'll create a PR for that.
