### ISSUE TITLE
The page has navigated to an other page and this navigation expired

### ISSUE THREAD

**Issue by AngelOfTerror** [chrome-php/headless-chromium-php#40]
Good day all,

The following was installed;
```
root@server003:/var/www/html_test# composer require chrome-php/chrome
sudo apt-get install chromium-browser
```

The following works perfectly:
```
echo '<pre>';
require_once('vendor/autoload.php');
use HeadlessChromium\BrowserFactory;
$factory = new BrowserFactory('chromium-browser --ignore-certificate-errors');
$browser = $factory->createBrowser([
      'debugLogger'     => 'php://stdout'
]);
$page = $browser->createPage();
$page->navigate('https://www.google.nl/')->waitForNavigation();
$value = $page->evaluate('document.querySelector("input[name=\"btnK\"]").value')->getReturnValue();
var_dump($value);
```

But then when I run the following:
```
echo '<pre>';
require_once('vendor/autoload.php');
use HeadlessChromium\BrowserFactory;
$factory = new BrowserFactory('chromium-browser --ignore-certificate-errors');
$browser = $factory->createBrowser([
		'debugLogger'     => 'php://stdout'
]);

$page = $browser->createPage();
$page->navigate('https://ip-address:8443/login')->waitForNavigation();
$evaluation = $page->evaluate(
'(() => {
        document.querySelector("#username").value = "***********";
        document.querySelector("#password").value = "***********";
        document.querySelector("form[name=\"login\"]").submit();
    })()'
);
$evaluation->waitForPageReload();
$value = $page->evaluate('document.querySelector(".duration .ng-binding").innerHTML')->getReturnValue();
var_dump($value);
```

The following error is generated:

```
Fatal error:  Uncaught HeadlessChromium\Exception\NavigationExpired: The page has navigated to an other page and this navigation expired in /var/www/html_test/vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php:165
Stack trace:
#0 /var/www/html_test/vendor/chrome-php/chrome/src/Utils.php(51): HeadlessChromium\PageUtils\PageNavigation->navigationComplete('load')
#1 /var/www/html_test/vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php(109): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator))
#2 /var/www/html_test/tst.php(41): HeadlessChromium\PageUtils\PageNavigation->waitForNavigation()
#3 {main}
  thrown in /var/www/html_test/vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php on line 165
```

Looking through the closed issues, I modified the createBrowser() call like this:

```
$browser = $factory->createBrowser([
		'headless'        => false,         // disable headless mode
		'connectionDelay' => 0.8,           // add 0.8 second of delay between each instruction sent to chrome,
		'debugLogger'     => 'php://stdout'
]);
```

Now the following is shown:

```
Fatal error:  Uncaught HeadlessChromium\Exception\NavigationExpired: The page has navigated to an other page and this navigation expired in /var/www/html_test/vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php:165
Stack trace:
#0 /var/www/html_test/vendor/chrome-php/chrome/src/Utils.php(51): HeadlessChromium\PageUtils\PageNavigation->navigationComplete('load')
#1 /var/www/html_test/vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php(109): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator))
#2 /var/www/html_test/tst.php(41): HeadlessChromium\PageUtils\PageNavigation->waitForNavigation()
#3 {main}
  thrown in /var/www/html_test/vendor/chrome-php/chrome/src/PageUtils/PageNavigation.php on line 165
```

Does anyone have any ideas?

Thank you very much.

**Comment by gsouf** [comment]
Hi @AngelOfTerror 

Does the page you load "'https://ip-address:8443/login'" redirects to another page?

**Comment by AngelOfTerror** [comment]
Hello @gsouf ,

This (/login) is the vendors login page, it should only redirect until after logging in. 
If I reduce the code to only visit the page, and take a screenshot - same error appears. No screenshot being saved.

```
$page = $browser->createPage();
$page->navigate('https://ip-address:8443/login')->waitForNavigation();
$page->screenshot()->saveToFile('/var/www/html_test/one.png');
$browser->close();
```

The eventual URL I want to visit is something else: https://ip-address:8443/something/randomnumber
It will show me the login box, and after login show the actual data. But as that showed me an error, I tried to go to the login page - which shouldn't redirect anywhere until after login.

This is a web-gui to an application, which has an API. But one of the most important values we can't export. So that is I'm looking to scrape of the website. 

Would this not be possible if a redirect is required? Not sure it is, but lets assume it does.

**Comment by gsouf** [comment]
@AngelOfTerror I actually need to know what produces the issue. With the details you provided I could not reproduce it. 

Could you please provide me with the full log generated by the script?

**Comment by AngelOfTerror** [comment]
Where would I find the log exactly? All I see on-screen, is the provided stack-trace.

**Comment by gsouf** [comment]
When you create the browser, can you please do that:

```php
$browser = $factory->createBrowser([
      'debugLogger'     =>fopen('/tmp/chrome-log.txt', 'a')
]);
```

It will write logs in the file ``/tmp/chrome-log.txt``. Then you can send that file

**Comment by AngelOfTerror** [comment]
Like that, Ok, I've changed the "headless" to 'true', as with 'false' the log file did not generate anything else then what the PHP error showed.

```
require_once('vendor/autoload.php');
use HeadlessChromium\BrowserFactory;

$factory = new BrowserFactory('chromium-browser --ignore-certificate-errors');
$browser = $factory->createBrowser([
		'headless'        => true,         // disable headless mode
		'connectionDelay' => 3.8,           // add 0.8 second of delay between each instruction sent to chrome,
		'debugLogger'     =>fopen('/var/www/html_test/chrome-log.txt', 'a'),
		'debug' => true,
		'enableImages' => false,
		'ignoreCertificateErrors' => true
]);

$page = $browser->createPage();
$page->navigate('https://server-ip-address:8443/something/530')->waitForNavigation();

$evaluation = $page->evaluate(
'(() => {
        document.querySelector("#username").value = "*****";
        document.querySelector("#password").value = "*****";
        document.querySelector("form[name=\"login\"]").submit();
    })()'
);

$evaluation->waitForPageReload();

$value = $page->evaluate('document.querySelector(".duration .ng-binding").innerHTML')->getReturnValue();
var_dump($value);

$browser->close();
exit;
```

That is what the PHP file looks like atm, attached the logging., 

[chrome-log.txt](https://github.com/chrome-php/headless-chromium-php/files/2438786/chrome-log.txt)

**Comment by gsouf** [comment]
Hi @AngelOfTerror 

I think that version  ``0.3.0`` should fix it. Can you upgrade and try again please?

**Comment by Amirpirmoradian** [comment]
hey

I have the same problem it happens randomly.
sometimes when I try to open a website it will open successfully but sometimes it produces this error.

can somebody help, please?

this is driving me crazy. 

:||

and what the reason for this error in the first place?
