### ISSUE TITLE
Timeout issue for opening the browser

### ISSUE THREAD

**Issue by bryan-ente** [chrome-php/headless-chromium-php#416]
So I am trying to open a Chromium, but it just times out. I got a script, which starts the built-in PHP webserver and then executes the PHP file, which starts the Chromium. here's the output of the PHP Log: 
```
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (5sec) in C:\Users\USER\repos\custify-copy\custify\vendor\chrome-php\chrome\src\Utils.php:71
Stack trace:
#0 C:\Users\USER\repos\custify-copy\custify\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(115): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator))
#1 C:\Users\USER\repos\custify-copy\custify\vendor\chrome-php\chrome\src\Communication\Session.php(89): HeadlessChromium\Communication\ResponseReader->waitForResponse(5000)
#2 C:\Users\USER\repos\custify-copy\custify\vendor\chrome-php\chrome\src\Browser.php(170): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#3 C:\Users\USER\repos\custify-copy\custify\start\startChromium.php(15): HeadlessChromium\Browser->createPage()
#4 {main}
  thrown in C:\Users\USER\repos\custify-copy\custify\vendor\chrome-php\chrome\src\Utils.php on line 71

```

My code which starts the Browser is the following:

```php
<?php

require_once "C:\\Users\\USER\\repos\\custify-copy\\custify" .  "/vendor/autoload.php";
require_once "C:\\Users\\USER\\repos\\custify-copy\\custify" . "/api/v1/inc/loader.php";
use HeadlessChromium\BrowserFactory;
use Custify\Custify;

$custify = new Custify;
$port = $custify->get_ini()["general"]["port"];

$browserFactory = new BrowserFactory("C:\\Users\\USER\\repos\\custify-copy\\custify\\chrome\\chrome-win\\chrome.exe");

$browser = $browserFactory->createBrowser(['connectionDelay' => 10]);

$page = $browser->createPage();
$page->navigate("http://localhost:{$port}")->waitForNavigation();

?>
```

And here's the script starting the server and executing the PHP script from above:

```sh
#!/bin/bash
port=$(<PORT.txt)
pwd=$(pwd)
path=$(dirname $pwd)

nohup php -S localhost:$port -t "$path" > phpd.log 2>&1 &
php startChromium.php
```

Any ideas, why it doesn't work? Thanks in advance!

**Comment by enricodias** [comment]
Can you share the debug log?
