### ISSUE TITLE
got OperationTimedOut exception when creating browser

### ISSUE THREAD

**Issue by weimily** [chrome-php/headless-chromium-php#425]
Hi,  
There are error log & debug log:
```
ERROR: Operation timed out after 5s.
#0 /code/vendor/chrome-php/chrome/src/Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(5000000)
#1 /code/vendor/chrome-php/chrome/src/Communication/ResponseReader.php(115): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator))
#2 /code/vendor/chrome-php/chrome/src/Communication/Connection.php(270): HeadlessChromium\Communication\ResponseReader->waitForResponse(5000)
#3 /code/vendor/chrome-php/chrome/src/Browser.php(84): HeadlessChromium\Communication\Connection->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#4 /code/vendor/chrome-php/chrome/src/Browser/ProcessAwareBrowser.php(26): HeadlessChromium\Browser->__construct(Object(HeadlessChromium\Communication\Connection))
#5 /code/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(162): HeadlessChromium\Browser\ProcessAwareBrowser->__construct(Object(HeadlessChromium\Communication\Connection), Object(HeadlessChromium\Browser\BrowserProcess))
```
```
[2022-09-02T12:15:01.020744+08:00] chrome.DEBUG: process: initializing
[2022-09-02T12:15:01.061869+08:00] chrome.DEBUG: process: using directory: /tmp/chromium-php-K4cFBM
[2022-09-02T12:15:01.062117+08:00] chrome.DEBUG: process: starting process: 'google-chrome-stable' '--remote-debugging-port=0' '--disable-background-networking' '--disable-background-timer-throttling' '--disable-client-side-phishing-detection' '--disable-hang-monitor' '--disable-popup-blocking' '--disable-prompt-on-repost' '--disable-sync' '--disable-translate' '--disable-features=ChromeWhatsNewUI' '--metrics-recording-only' '--no-first-run' '--safebrowsing-disable-auto-update' '--enable-automation' '--password-store=basic' '--use-mock-keychain' '--headless' '--disable-gpu' '--font-render-hinting=none' '--hide-scrollbars' '--mute-audio' '--no-sandbox' '--user-data-dir=/tmp/chromium-php-K4cFBM'
[2022-09-02T12:15:01.073518+08:00] chrome.DEBUG: process: waiting for 30 seconds for startup
[2022-09-02T12:15:06.264507+08:00] chrome.DEBUG: process: chrome output:[0902/041505.646598:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory [0902/041506.249907:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2022-09-02T12:15:06.296109+08:00] chrome.DEBUG: process: ignoring output:[0902/041505.646598:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2022-09-02T12:15:06.296176+08:00] chrome.DEBUG: process: ignoring output:[0902/041506.249907:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2022-09-02T12:15:07.082510+08:00] chrome.DEBUG: process: chrome output:DevTools listening on ws://127.0.0.1:42307/devtools/browser/4752c998-748e-44da-9856-86ec9bad16cc
[2022-09-02T12:15:07.113843+08:00] chrome.DEBUG: process: ✓ accepted output
[2022-09-02T12:15:07.113911+08:00] chrome.DEBUG: process: connecting using ws://127.0.0.1:42307/devtools/browser/4752c998-748e-44da-9856-86ec9bad16cc
[2022-09-02T12:15:07.287740+08:00] chrome.DEBUG: socket(1): connecting
[2022-09-02T12:15:10.375752+08:00] chrome.DEBUG: socket(1): ✓ connected
[2022-09-02T12:15:11.521205+08:00] chrome.DEBUG: socket(1): → sending data:{"id":1,"method":"Target.setDiscoverTargets","params":{"discover":true}}
[2022-09-02T12:15:33.254203+08:00] chrome.DEBUG: process: killing chrome
[2022-09-02T12:15:34.295993+08:00] chrome.DEBUG: process: trying to close chrome gracefully
Fatal error: Uncaught Error: Call to a member function sendCloseMessage() on null in /code/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:210
Stack trace:
#0 [internal function]: HeadlessChromium\\Browser\\BrowserProcess->kill()
#1 {main}
  thrown in /code/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php on line 210
```

my Dockerfile
```dockerfile
# syntax=docker/dockerfile:experimental

FROM php:8.1-cli

RUN apt-get update && apt-get install -y \
        wget \
        gnupg \
        git \
        ssh \
        libsodium-dev \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update && apt-get install -y \
        google-chrome-stable \
        libxss1 \
          --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install sodium \
    && docker-php-ext-enable sodium

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

COPY . /code
RUN --mount=type=ssh cd /code && composer install --no-dev --optimize-autoloader

CMD ["php", "/script.php"]
```
script.php
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory('google-chrome-stable');
$browser = $browserFactory->createBrowser(['noSandbox' => true, 'debugLogger' => 'php://stdout']);

// ...
```

Google Chrome: amd64 105.0.5195.52-1  
Chrome-php: 1.7.0

I tried to set `sendSyncDefaultTimeout = 30000`, and then got the same log.  
Please let me know what i am doing wrong here?  
Thanks a lot!

**Comment by enricodias** [comment]
@weimily can you share how did you solve the problem to help anyone who may face the same issue in the future?

**Comment by weimily** [comment]
I did nothing, but the error log no longer appear after next deploy.
And I got other error logs.
Finally, it works after increasing ram.

**Comment by huelsgp27** [comment]
I got same issue

**Comment by thierrymaasdam** [comment]
Are you on Apple Silicon? This problem was solved for me by going to Docker Desktop and checking the `Use Rosetta for x86_64/amd64 emulation on Apple Silicon` checkbox, followed by `Apply & Restart`. 

The crux was in the warning that I got when launching the Docker container: 
```
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Good luck all!

**Comment by NJPod** [comment]
> Are you on Apple Silicon? This problem was solved for me by going to Docker Desktop and checking the `Use Rosetta for x86_64/amd64 emulation on Apple Silicon` checkbox, followed by `Apply & Restart`.
> 
> The crux was in the warning that I got when launching the Docker container:
> 
> ```
> The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> ```
> 
> Good luck all!

@thierrymaasdam this solved the issue for my work colleague. We both run macs and I couldn't figure why it worked on my mac and not his. Turns out I had this feature enabled and he didn't.

Thanks for this.
