### ISSUE TITLE
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (50sec)

### ISSUE THREAD

**Issue by lokutus24** [chrome-php/headless-chromium-php#428]
```
function chromeWithClick($url){

    echo "download this Url with Chrome: ".$url."\n";

    // replace default 'chrome' with 'chromium-browser'
    $browserFactory = new BrowserFactory('/usr/bin/google-chrome');

    $browser = $browserFactory->createBrowser([
        'noSandbox' => true,
        'debugLogger' => 'php://stdout',
        //'startupTimeout' => 40,
        //'sendSyncDefaultTimeout' => 15000,
        'keepAlive' => true,
        'headless' => true,
        'connectionDelay' => 2000,
        //'enableImages' => true,
        'ignoreCertificateErrors' => true, // disable headless mode
    ]);

    try {

        $page = $browser->createPage();

        $page->navigate($url)->waitForNavigation(Page::DOM_CONTENT_LOADED, 60000);

        /*$page->setCookies([
            Cookie::create('name', 'value', ['expires'])
        ])->await();*/

        $page->evaluate('$("#dropdown-amount").val("10000").trigger("change")')->waitForPageReload(Page::DOM_CONTENT_LOADED, 50000);
        $pageHtml = $page->getHtml();

        // screenshot - Say "Cheese"! 😄
        //$page->screenshot()->saveToFile('/home/emanage/public_html/foo/bar.png');

        // pdf
        $page->pdf(['printBackground' => true])->saveToFile('/home/emanage/public_html/foo/bar.pdf');

        file_put_contents('/home/emanage/public_html/foo/page.html', $pageHtml);

    }finally{

        // bye
        $browser->close();
    }

    return $pageHtml;
}
```

i got this log:

[2022-09-07 07:34:09] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Network.dataReceived\",\"params\":{\"requestId\":\"91592.73\",\"timestamp\":4410197.756401,\"dataLength\":2644,\"encodedDataLength\":2644}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:09] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Network.dataReceived\",\"params\":{\"requestId\":\"91592.73\",\"timestamp\":4410197.756506,\"dataLength\":7000,\"encodedDataLength\":7000}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:09] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Network.dataReceived
[2022-09-07 07:34:09] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Network.dataReceived
[2022-09-07 07:34:09] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Network.dataReceived\",\"params\":{\"requestId\":\"91592.73\",\"timestamp\":4410197.780302,\"dataLength\":1192,\"encodedDataLength\":1192}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:09] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Network.dataReceived\",\"params\":{\"requestId\":\"91592.73\",\"timestamp\":4410197.780522,\"dataLength\":14520,\"encodedDataLength\":14520}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:09] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Network.dataReceived\",\"params\":{\"requestId\":\"91592.73\",\"timestamp\":4410197.780623,\"dataLength\":25005,\"encodedDataLength\":25005}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:09] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Network.dataReceived
[2022-09-07 07:34:09] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Network.dataReceived
[2022-09-07 07:34:09] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Network.dataReceived
[2022-09-07 07:34:09] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Network.loadingFinished\",\"params\":{\"requestId\":\"91592.73\",\"timestamp\":4410197.780652,\"encodedDataLength\":86581,\"shouldReportCorbBlocking\":false}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:09] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Network.loadingFinished
[2022-09-07 07:34:10] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"45BB8075A7B24FC113DB0452EFFA8D1D\",\"loaderId\":\"48319BF6EE79990A218CECF1ED46A524\",\"name\":\"networkIdle\",\"timestamp\":4410197.781385}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:10] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Page.lifecycleEvent
[2022-09-07 07:34:14] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"DE9EF7EA90A85C32351A4D747F69AA3D","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"45BB8075A7B24FC113DB0452EFFA8D1D\",\"loaderId\":\"48319BF6EE79990A218CECF1ED46A524\",\"name\":\"InteractiveTime\",\"timestamp\":4410202.210285}}","targetId":"45BB8075A7B24FC113DB0452EFFA8D1D"}}
[2022-09-07 07:34:14] DEBUG session(DE9EF7EA90A85C32351A4D747F69AA3D): ⇶ dispatching method:Page.lifecycleEvent
[2022-09-07 07:34:56] DEBUG process: killing chrome
[2022-09-07 07:34:56] DEBUG process: trying to close chrome gracefully
[2022-09-07 07:34:56] DEBUG socket(1): → sending data:{"id":18,"method":"Browser.close","params":{}}
[2022-09-07 07:34:56] DEBUG socket(1): ← receiving data:{"id":18,"result":{}}
[2022-09-07 07:34:56] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"45BB8075A7B24FC113DB0452EFFA8D1D","type":"page","title":"Term\u00e9kek - Versele-Laga","url":"https://www.versele-laga.com/hu/hu/az-%C3%B6n-%C3%A1llat%C3%A1nak/ketrecben-%C3%A9s-mad%C3%A1rh%C3%A1zban-tartott-madarak/term%C3%A9kek/","attached":false,"canAccessOpener":false,"browserContextId":"6AEFFC774EB0CB786E7D08F378FEDE6F"}}}
[2022-09-07 07:34:56] DEBUG socket(1): disconnecting
[2022-09-07 07:34:56] DEBUG socket(1): ✓ disconnected
[2022-09-07 07:34:56] DEBUG process: waiting for process to close
[2022-09-07 07:34:56] DEBUG process: cleaning temporary resources:/tmp/chromium-php-OiTT98
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (50sec) in /home/emanage/public_html/vendor/chrome-php/chrome/src/Utils.php:71
Stack trace:
#0 /home/emanage/public_html/vendor/chrome-php/chrome/src/Page.php(387): HeadlessChromium\Utils::tryWithTimeout()
#1 /home/emanage/public_html/vendor/chrome-php/chrome/src/PageUtils/PageEvaluation.php(67): HeadlessChromium\Page->waitForReload()
#2 /home/emanage/public_html/vese.php(106): HeadlessChromium\PageUtils\PageEvaluation->waitForPageReload()
#3 /home/emanage/public_html/vese.php(328): chromeWithClick()
#4 {main}
  thrown in /home/emanage/public_html/vendor/chrome-php/chrome/src/Utils.php on line 71

**Comment by seitymoe** [comment]
I've got the same error. I tried to get a screenshot and got the same timed out error.
I tried with these combinations and they all returned the same error.
chrome v.103 and chrome-php v.1.61
chrome v.80 and chrome-php v.1.6.1
chrome v.80 and chrome-php v.1.7.1

Are there any solutions..?

**Comment by huelsgp27** [comment]
Same issue.

**Comment by enricodias** [comment]
You are evaluating a js script and then waiting for a page reload using the `Page::DOM_CONTENT_LOADED` event. This event is not getting fired in the specified timeout. This is not a bug in the lib nor in chrome and we can't even reproduce it without the actual url.

My guess would be that the script evaluation on that particular url doesn't result in a reload. Debug it using the browser console logs or even test it without the headless mode to see the gui if it actually reloads. Keep in mind that there are different load events as well.
