### ISSUE TITLE
Scrolling the page too far will cause a timeout error.

### ISSUE THREAD

**Issue by ms-smz** [chrome-php/headless-chromium-php#441]
```
$page->mouse()->scrollDown(2000);
```
```
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 2s. in vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Stack trace:
#0 vendor\chrome-php\chrome\src\Utils.php(78): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(2000000)
#1 vendor\chrome-php\chrome\src\Communication\ResponseReader.php(115): HeadlessChromium\Utils::tryWithTimeout(2000000, Object(Generator))
#2 vendor\chrome-php\chrome\src\PageUtils\ResponseWaiter.php(51): HeadlessChromium\Communication\ResponseReader->waitForResponse(2000)
#3 vendor\chrome-php\chrome\src\PageUtils\ResponseWaiter.php(74): HeadlessChromium\PageUtils\ResponseWaiter->await(NULL)
#4 vendor\chrome-php\chrome\src\PageUtils\PageLayoutMetrics.php(126): in vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php on line 18
```

I think the default timeout value is too small as the cause.

vendor\chrome-php\chrome\src\Communication\ResponseReader.php
```
public function waitForResponse(int $timeout = null): Response
{
    if ($this->hasResponse()) {
        return $this->getResponse();
    }

    // default 2000ms
    $timeout = $timeout ?? 2000;

    return Utils::tryWithTimeout($timeout * 1000, $this->waitForResponseGenerator());
}
```
I would like to be able to specify a separate default value here, or the default value should be changed to 15000 ms.

**Comment by momala454** [comment]
https://github.com/chrome-php/chrome/issues/387
