### ISSUE TITLE
Freeze when using waitForDebuggerOnStart

### ISSUE THREAD

**Issue by momala454** [chrome-php/headless-chromium-php#463]
Using the following code to pause when a target is created and send Runtime.runIfWaitingForDebugger if it's `waitingForDebugger` will cause the browser to freeze and the script timeout

```php
<?php

error_reporting(E_ALL);
ini_set('display_errors', true); 
set_time_limit(0);
chdir(__DIR__);
ini_set('output_buffering','off');
ob_implicit_flush(true);

require_once('vendor/autoload.php');

$browserFactory = new \HeadlessChromium\BrowserFactory();

// starts headless chrome
$browser = $browserFactory->createBrowser([
  'userAgent'					=>	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'headless'                    =>  true,
  'debugLogger'     			=> 'php://stdout',
  'customFlags'                 => ['--no-sandbox'],
]);

$browser->getConnection()->on("method:Target.attachedToTarget", function($event) use ($browser) {
    print_r($event);
    if ($event['waitingForDebugger']) {
        print_r($browser->getTarget($event['targetInfo']['targetId'])->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message('Runtime.runIfWaitingForDebugger', [])), true);
    }
});

$browser->getConnection()->sendMessageSync(new \HeadlessChromium\Communication\Message('Target.setAutoAttach', ['autoAttach' => true, 'waitForDebuggerOnStart' => true, 'flatten' => true]));



try {
    // creates a new page and navigate to an URL
    $page = $browser->createPage();

    $page->navigate('http://example.com/')->waitForNavigation();
} finally {
    // bye
    //sleep(230);
    echo 'close';
    $browser->close();
}
```

logs
```
[2023-01-05 09:44:34] DEBUG Factory: chrome version: 84
[2023-01-05 09:44:34] DEBUG process: initializing
[2023-01-05 09:44:34] DEBUG process: using directory: ............chr15CC.tmp
[2023-01-05 09:44:34] DEBUG process: starting process: "C:/Program Files/Google/Chrome/Application/chrome.exe" --remote-debugging-port=0 --disable-background-networking --disable-background-timer-throttling --disable-client-side-phishing-detection --disable-default-apps --disable-extensions --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" --no-sandbox --user-data-dir=..................\chr15CC.tmp
[2023-01-05 09:44:34] DEBUG process: waiting for 30 seconds for startup
[2023-01-05 09:44:34] DEBUG process: chrome output:DevTools listening on ws://127.0.0.1:52679/devtools/browser/4a7830ea-2c1a-431f-b01c-55bdae904e77
[2023-01-05 09:44:34] DEBUG process: ✓ accepted output
[2023-01-05 09:44:34] DEBUG process: connecting using ws://127.0.0.1:52679/devtools/browser/4a7830ea-2c1a-431f-b01c-55bdae904e77
[2023-01-05 09:44:34] DEBUG socket(1): connecting
[2023-01-05 09:44:34] DEBUG socket(1): ✓ connected
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":1,"method":"Target.setDiscoverTargets","params":{"discover":true}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"1298CA3B3C558FB147DCE5EC00CD3D60","type":"page","title":"Nouvel onglet","url":"chrome://newtab/","attached":false,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"CB94DFD122CEFF107C88A2556C7D8B06","type":"background_page","title":"Google Hangouts","url":"chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html","attached":false,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":1,"result":{}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":2,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"1298CA3B3C558FB147DCE5EC00CD3D60","type":"page","title":"Nouvel onglet","url":"chrome://newtab/","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.attachedToTarget","params":{"sessionId":"DA1DC7A5E4740A512A46B4C95E3F6F84","targetInfo":{"targetId":"1298CA3B3C558FB147DCE5EC00CD3D60","type":"page","title":"Nouvel onglet","url":"chrome://newtab/","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"},"waitingForDebugger":false}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"CB94DFD122CEFF107C88A2556C7D8B06","type":"background_page","title":"Google Hangouts","url":"chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.attachedToTarget","params":{"sessionId":"B4AFD678CF3C88132F19D04879827372","targetInfo":{"targetId":"CB94DFD122CEFF107C88A2556C7D8B06","type":"background_page","title":"Google Hangouts","url":"chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"},"waitingForDebugger":false}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":2,"result":{}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.attachedToTarget
Array
(
    [sessionId] => DA1DC7A5E4740A512A46B4C95E3F6F84
    [targetInfo] => Array
        (
            [targetId] => 1298CA3B3C558FB147DCE5EC00CD3D60
            [type] => page
            [title] => Nouvel onglet
            [url] => chrome://newtab/
            [attached] => 1
            [canAccessOpener] =>
            [browserContextId] => F5CC7CC2612F41178E761B0F2056957D
        )

    [waitingForDebugger] =>
)
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.attachedToTarget
Array
(
    [sessionId] => B4AFD678CF3C88132F19D04879827372
    [targetInfo] => Array
        (
            [targetId] => CB94DFD122CEFF107C88A2556C7D8B06
            [type] => background_page
            [title] => Google Hangouts
            [url] => chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html
            [attached] => 1
            [canAccessOpener] =>
            [browserContextId] => F5CC7CC2612F41178E761B0F2056957D
        )

    [waitingForDebugger] =>
)
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":3,"method":"Target.createTarget","params":{"url":"about:blank"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"CB94DFD122CEFF107C88A2556C7D8B06","type":"background_page","title":"Google Hangouts","url":"chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"8F3D19BB59AF2F31294D95A0D64873A9","type":"page","title":"","url":"about:blank","attached":false,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"8F3D19BB59AF2F31294D95A0D64873A9","type":"page","title":"","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.attachedToTarget","params":{"sessionId":"6BD7B9D227AF2C9BAB4C00EE72459C7E","targetInfo":{"targetId":"8F3D19BB59AF2F31294D95A0D64873A9","type":"page","title":"","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"},"waitingForDebugger":true}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.attachedToTarget
Array
(
    [sessionId] => 6BD7B9D227AF2C9BAB4C00EE72459C7E
    [targetInfo] => Array
        (
            [targetId] => 8F3D19BB59AF2F31294D95A0D64873A9
            [type] => page
            [title] =>
            [url] => about:blank
            [attached] => 1
            [canAccessOpener] =>
            [browserContextId] => F5CC7CC2612F41178E761B0F2056957D
        )

    [waitingForDebugger] => 1
)
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":4,"method":"Target.attachToTarget","params":{"targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":3,"result":{"targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"8F3D19BB59AF2F31294D95A0D64873A9","type":"page","title":"about:blank","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"1298CA3B3C558FB147DCE5EC00CD3D60","type":"page","title":"Nouvel onglet","url":"chrome://newtab/","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.attachedToTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","targetInfo":{"targetId":"8F3D19BB59AF2F31294D95A0D64873A9","type":"page","title":"about:blank","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"},"waitingForDebugger":false}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":4,"result":{"sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.attachedToTarget
Array
(
    [sessionId] => 059BE1F231B6ED083AD78276D47453EE
    [targetInfo] => Array
        (
            [targetId] => 8F3D19BB59AF2F31294D95A0D64873A9
            [type] => page
            [title] => about:blank
            [url] => about:blank
            [attached] => 1
            [canAccessOpener] =>
            [browserContextId] => F5CC7CC2612F41178E761B0F2056957D
        )

    [waitingForDebugger] =>
)
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":6,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":5,\"method\":\"Runtime.runIfWaitingForDebugger\",\"params\":[]}","sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":6,"result":{}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"id\":5,\"result\":{}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":8,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":7,\"method\":\"Page.getFrameTree\",\"params\":[]}","sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":8,"result":{}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"id\":7,\"result\":{\"frameTree\":{\"frame\":{\"id\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"url\":\"about:blank\",\"domainAndRegistry\":\"\",\"securityOrigin\":\"://\",\"mimeType\":\"text/html\",\"adFrameStatus\":{\"adFrameType\":\"none\"},\"secureContextType\":\"InsecureScheme\",\"crossOriginIsolatedContextType\":\"NotIsolated\",\"gatedAPIFeatures\":[]}}}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":10,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":9,\"method\":\"Page.enable\",\"params\":[]}","sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":10,"result":{}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"id\":9,\"result\":{}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":12,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":11,\"method\":\"Network.enable\",\"params\":[]}","sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"id\":11,\"error\":{\"code\":-32602,\"message\":\"Invalid parameters\",\"data\":\"Failed to deserialize params - CBOR: map start expected at position 7\"}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":12,"result":{}}
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":14,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":13,\"method\":\"Runtime.enable\",\"params\":[]}","sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":14,"result":{}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Runtime.executionContextCreated\",\"params\":{\"context\":{\"id\":1,\"origin\":\"://\",\"name\":\"\",\"uniqueId\":\"-1263939199103582868.6294181503348679001\",\"auxData\":{\"isDefault\":true,\"type\":\"default\",\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\"}}}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"id\":13,\"result\":{}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Runtime.executionContextCreated
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":16,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":15,\"method\":\"Page.setLifecycleEventsEnabled\",\"params\":{\"enabled\":true}}","sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":16,"result":{}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"name\":\"commit\",\"timestamp\":43529.414941}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"name\":\"DOMContentLoaded\",\"timestamp\":43529.415014}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"name\":\"load\",\"timestamp\":43529.415809}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"name\":\"networkAlmostIdle\",\"timestamp\":43529.416104}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"name\":\"networkIdle\",\"timestamp\":43529.416104}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"id\":15,\"result\":{}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:34] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Page.lifecycleEvent
[2023-01-05 09:44:34] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Page.lifecycleEvent
[2023-01-05 09:44:34] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Page.lifecycleEvent
[2023-01-05 09:44:34] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Page.lifecycleEvent
[2023-01-05 09:44:34] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Page.lifecycleEvent
[2023-01-05 09:44:34] DEBUG socket(1): → sending data:{"id":18,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":17,\"method\":\"Page.navigate\",\"params\":{\"url\":\"http:\\\/\\\/example.com\\\/\",\"transitionType\":\"address_bar\"}}","sessionId":"059BE1F231B6ED083AD78276D47453EE"}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"id":18,"result":{}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"A3B39692E16646994E7E084989A91963","type":"iframe","title":"","url":"","attached":false,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"A3B39692E16646994E7E084989A91963","type":"iframe","title":"chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=","url":"chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=","attached":false,"canAccessOpener":false,"browserContextId":"F5CC7CC2612F41178E761B0F2056957D"}}}
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2023-01-05 09:44:34] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2023-01-05 09:44:35] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"name\":\"networkAlmostIdle\",\"timestamp\":43529.416104}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:35] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"059BE1F231B6ED083AD78276D47453EE","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"frameId\":\"8F3D19BB59AF2F31294D95A0D64873A9\",\"loaderId\":\"7CBC92D55D9E3B14F0FB9AF9D9E72476\",\"name\":\"networkIdle\",\"timestamp\":43529.416104}}","targetId":"8F3D19BB59AF2F31294D95A0D64873A9"}}
[2023-01-05 09:44:35] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Page.lifecycleEvent
[2023-01-05 09:44:35] DEBUG session(059BE1F231B6ED083AD78276D47453EE): ⇶ dispatching method:Page.lifecycleEvent
close[2023-01-05 09:45:04] DEBUG process: killing chrome
[2023-01-05 09:45:04] DEBUG process: trying to close chrome gracefully
[2023-01-05 09:45:04] DEBUG socket(1): → sending data:{"id":19,"method":"Browser.close","params":[]}
[2023-01-05 09:45:04] DEBUG socket(1): ← receiving data:{"id":19,"result":{}}
[2023-01-05 09:45:04] DEBUG socket(1): ← receiving data:{"method":"Inspector.detached","params":{"reason":"Render process gone."},"sessionId":"B4AFD678CF3C88132F19D04879827372"}
[2023-01-05 09:45:04] DEBUG socket(1): disconnecting
[2023-01-05 09:45:04] DEBUG socket(1): ✓ disconnected
[2023-01-05 09:45:04] DEBUG process: waiting for process to close
[2023-01-05 09:45:04] DEBUG process: cleaning temporary resources:..........chr15CC.tmp

Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (30sec) in \vendor\chrome-php\chrome\src\Utils.php:65
Stack trace:
#0 \vendor\chrome-php\chrome\src\PageUtils\PageNavigation.php(122): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator))
#1 \testBug.php(38): HeadlessChromium\PageUtils\PageNavigation->waitForNavigation()
#2 {main}
  thrown in \vendor\chrome-php\chrome\src\Utils.php on line 65
[2023-01-05 09:45:05] DEBUG process: killing chrome
[2023-01-05 09:45:05] DEBUG process: chrome already killed, ignoring`
```

if i send `Runtime.runIfWaitingForDebugger` without checking for the presence of `waitingForDebugger` (it could be the way we need to do it), it goes into an infinite loop of attach to target

**Comment by momala454** [comment]
calling getSession using the sessionId fixes the problem. I wonder if it could be improved directly on the library

   ` print_r($browser->getTarget($event['targetInfo']['targetId'])->getSession($event['sessionId'])->sendMessageSync(new \HeadlessChromium\Communication\Message('Runtime.runIfWaitingForDebugger', [])), true);
`
