### ISSUE TITLE
Page.startScreencast + spamming Connection::readData causes SendMessageSync to fail

### ISSUE THREAD

**Issue by divinity76** [chrome-php/headless-chromium-php#560]
on Windows 10 (but /not/ Ubuntu 22.04 Linux), starting a [Page.startScreencast](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast) then spamming `$page->getSession()->getConnection()->readData()` can cause a subsequent SendMessageSync to fail.

The really strange part is that this loop will trigger the crash
```php
while (microtime(true) < $target_time) {
    $page->getSession()->getConnection()->readData();
    usleep(1);
}
```
and this loop does not:
```php
while (microtime(true) < $target_time) {
    $page->getSession()->getConnection()->readData();
}
```
- removing the usleep makes it not crash, for some reason.

stack trace:
```php
$ php crashtest.php
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 5s. in C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Stack trace:
#0 C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(5000000)
#1 C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(114): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator))
#2 C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Communication\Session.php(89): HeadlessChromium\Communication\ResponseReader->waitForResponse(5000)
#3 C:\cygwin64\home\hans\test\crashtest.php(34): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#4 {main}
  thrown in C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php on line 18

Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 5s. in C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Stack trace:
#0 C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(5000000)
#1 C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(114): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator))
#2 C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Communication\Session.php(89): HeadlessChromium\Communication\ResponseReader->waitForResponse(5000)
#3 C:\cygwin64\home\hans\test\crashtest.php(34): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#4 {main}
  thrown in C:\cygwin64\home\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php on line 18


```
code:
```php
<?php

declare(strict_types=1);
require_once __DIR__ . "/vendor/autoload.php";
$browserFactory = new \HeadlessChromium\BrowserFactory(
    "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
);
$browser = $browserFactory->createBrowser([
    'headless' => true,
    //'debugLogger' => 'php://stdout', // will enable verbose mode
    'windowSize'   => [1920, 1080],
]);
$page = $browser->createPage();
$page->getSession()->on('method:Page.screencastFrame', function (array $params) use ($page): void {
    $page->getSession()->sendMessage(new \HeadlessChromium\Communication\Message(
        'Page.screencastFrameAck',
        [
            'sessionId' => $params['sessionId'],
        ]
    ));
});
$startScreencastResponse = $page->getsession()->sendMessageSync(new \HeadlessChromium\Communication\Message(
    'Page.startScreencast',
    array()
));

$navigate = $page->navigate('https://youtube.com/');
//$navigate->waitForNavigation(\HeadlessChromium\Page::NETWORK_IDLE);
$target_time = microtime(true) + 5;
while (microtime(true) < $target_time) {
    $page->getSession()->getConnection()->readData();
    usleep(1);
}
$page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message(
    'Page.stopScreencast',
    [
        'sessionId' => $startScreencastResponse->getData()['sessionId'],
    ]
));
```
- the actual crash happens in sending the stopScreencast message, but it fails depending on whether or not usleep(1) is present in the readData() loop 🤔
- using a target_time below 5 also prevents the crash, seemingly.. ( i have tested 1,2,3,4,5, 6 and it only crashes on 5 and 6)
- can reproduce on Windows 10 + PHP  8.2.12 + chrome-php/chrome 1.9.1 + Google Chrome 119.0.6045.160 
- can /not/ reproduce on Ubuntu 22.04 Linux + PHP 8.2.12 + chrome-php/chrome 1.9.1 + Chromium 119.0.6045.159

**Comment by divinity76** [comment]
> This issue has been automatically marked as stale because there has been no recent activity. It will be closed after 30 days if no further activity occurs. Thank you for your contributions.

well it hasn't been fixed: i can still reproduce it on Windows 10 + PHP 8.3.4 + chrome-php/chrome v1.10.0  + Google Chrome 122.0.6261.129:
```
C:\Users\hans\test>php reproduce.php

C:\Users\hans\test>php reproduce.php
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 5s. in C:\Users\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Stack trace:
#0 C:\Users\hans\test\vendor\chrome-php\chrome\src\Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(5000000)
#1 C:\Users\hans\test\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(114): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator))
#2 C:\Users\hans\test\vendor\chrome-php\chrome\src\Communication\Session.php(89): HeadlessChromium\Communication\ResponseReader->waitForResponse(5000)
#3 C:\Users\hans\test\reproduce.php(34): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#4 {main}
  thrown in C:\Users\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php on line 18

Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 5s. in C:\Users\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Stack trace:
#0 C:\Users\hans\test\vendor\chrome-php\chrome\src\Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(5000000)
#1 C:\Users\hans\test\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(114): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator))
#2 C:\Users\hans\test\vendor\chrome-php\chrome\src\Communication\Session.php(89): HeadlessChromium\Communication\ResponseReader->waitForResponse(5000)
#3 C:\Users\hans\test\reproduce.php(34): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#4 {main}
  thrown in C:\Users\hans\test\vendor\chrome-php\chrome\src\Exception\OperationTimedOut.php on line 18
```
- interestingly, it didn't happen the first time, but it did happen the second time.

**Comment by divinity76** [comment]
I think this issue should be excluded from stale bot: we don't know how to fix it, but it's still a real unfixed issue 🤔

And I believe it's responsible for occasional random un-reproducible failures on Windows scripts of mine, including scripts that does not use Page.startScreencast.
