### ISSUE TITLE
Looping over `querySelectorAll` results and performing actions throws `Uncaught DomException: -32000 - Could not find node with given id`

### ISSUE THREAD

**Issue by sanderdlm** [chrome-php/headless-chromium-php#594]
Sorry for the long yet vague title.

I've included a short reproducer:
```php
<?php

use HeadlessChromium\BrowserFactory;
use HeadlessChromium\Dom\Node;

require_once __DIR__ . '/vendor/autoload.php';

$browserFactory = new BrowserFactory();

$browser = $browserFactory->createBrowser([
    'headless' => false
]);

$page = $browser->getPages()[0];

$page->navigate('https://www.bergfreunde.eu/la-sportiva-testarossa-climbing-shoes/')->waitForNavigation();

$sizeOptions = $page->dom()->querySelectorAll('ul.varlist-select-size li');

/** @var Node $option */
foreach ($sizeOptions as $option) {
    $size = trim($option->getText());
    echo "Checking size $size\n";

    $mainPrice = $page->dom()->querySelector('[data-codecept="productPrice"]')->getText();
    echo "Main price: $mainPrice\n";
}
```

If I loop over my list of `li` items, and only print the content with `getText()`, the code runs fine.
If I loop over my list of `li` items, and only print the content of a random div somewhere else on the tab, the code runs fine.
But if I try to do both, I get the following error (after 1 run of the loop, so second pass):

```
PHP Fatal error:  Uncaught HeadlessChromium\Exception\DomException: -32000 - Could not find node with given id in /Users/marc434451/Sites/personal/shooz/vendor/chrome-php/chrome/src/Dom/Node.php:214
Stack trace:
#0 /Users/marc434451/Sites/personal/shooz/vendor/chrome-php/chrome/src/Dom/Node.php(138): HeadlessChromium\Dom\Node->assertNotError(Object(HeadlessChromium\Communication\Response))
#1 /Users/marc434451/Sites/personal/shooz/vendor/chrome-php/chrome/src/Dom/Node.php(156): HeadlessChromium\Dom\Node->getHTML()
#2 /Users/marc434451/Sites/personal/shooz/repro.php(22): HeadlessChromium\Dom\Node->getText()
#3 {main}
  thrown in /Users/marc434451/Sites/personal/shooz/vendor/chrome-php/chrome/src/Dom/Node.php on line 214
```

Probably just interacting with the nodes in a wrong way/order, but I couldn't find any info in the docs.

**Comment by stenas** [comment]
I have the same problem, it seems that something changed in the new version 1.12, rollback to version 1.11 and works again.

**Comment by stenas** [comment]
The problem continue on version 1.13.0. 
Any idea to solve the problem?

**Comment by blauweb** [comment]
Bumping up this issue. Same case here, bit different scenario. I querySelect all images in a dom container, and I then I loop through them via foreach. I am only able to perform actions on the first element (i click on the image, which updates the dom in another place), and then when I reach the second item, I am no longer able to interact with it, because the mentioned error happens.

EDIT:
I have found a "workaround" for myself. I store dom relevant IDs of the elements (which was possible in this case) in a separate array, and then utilize these in a foreach loop to trigger page wide querySelectors for the specific item and then interact with that item.
If the elements would not have ID i could use, I would base the logic on an abstract index mechanism (by taking the length of the found items).

I still think that an explanation, for why the error is happening, would be beneficial. It would be great if the documentation would include details on how to deal with dynamic/virtual doms.

**Comment by Sarke** [comment]
This is caused by CssSelector not escaping the double quotes.

**Comment by Seriyyy95** [comment]
The problem originally described in this Issue probably was related to version 1.11 and was fixed in version 1.12. Anyway, this reproducer gives an error only in 1.11 and works fine in 1.12 and 1.13. Here the original [issue](https://github.com/chrome-php/chrome/issues/469).

Previously, each time the `$page->dom()` method was called, a new `Dom` object was created, which made a request to the browser to get the ID of the root node. Due to the peculiarities of the Chrome browser, this led to the fact that `node_id` for all elements on the page was updated.

In version 1.12, the `$page->dom()` method returns the same `Dom` object that stores the root node ID obtained when the object was initially created. In order for the identifier to be updated when the page is updated, `Dom` listens to the `DOM.documentUpdated` event. When such event is received, the ID of the root node is updated, but IDs for all other nodes are considered stale and when trying to interact with such nodes, `StaleElementException` exception will be thrown.

There's not much further I can do because Chrome doesn't provide a way to keep track of updating regular node ids (or I don't know about such features).

> I have the same problem, it seems that something changed in the new version 1.12, rollback to version 1.11 and works again.

But if your code worked in 1.11 and does not work in 1.12, it is strange. Can you prepare a script to reproduce this? I don't know is it possible or not fix that, but it is interesting to understand why the error happens.

**Comment by stenas** [comment]
```php
$this->page->navigate($this->url.'FRM005RPOLCP_input.action')->waitForNavigation(Page::LOAD, $this->timeout);

$this->page->evaluate("$('#codigoCertidao').val('".$certificateCode."')");
$this->page->evaluate("$('form[name=frm]').attr('action', 'FRM005RPOLCP_validar.action').submit()")->waitForResponse($this->timeout);
sleep(5);
foreach($this->page->dom()->querySelectorAll('ul.errorMessage li') as $message) {
    $this->setErrors($message->getText());
}

if(!empty($this->getErrors())) return false;

$this->page->evaluate("$('form[name=frm]').attr('action', 'FRM005RPOLCP.action').submit();")->waitForResponse($this->timeout);

//set path temporay folder
$tempFolderPath = $this->tempFolder.DS.$certificateCode.DS;
if(!is_dir($tempFolderPath)) mkdir($tempFolderPath,775,true);
$this->page->setDownloadPath($tempFolderPath);
//copy to dms
$i = 0;

//add this line possible solution
$this->page->waitForReload(); 

foreach($this->page->dom()->querySelectorAll('a.downloadLink') as $link){
    $link->click();
    sleep(20);
    $i++;
}

```


This code submits data to two forms and on the last form page it is sent to a new page where it is possible to download files
When run the foreach the code return this exeception ````Uncaught DomException: -32000 - Could not find node with given id````

@Seriyyy95, when I read your comment, I remembered that the dom might not be up to date.
I put the function $this->page->waitForReload() before foreach
and the foreach did not return an exception.

I don't know if it's the best solution, but it works :)

**Comment by Seriyyy95** [comment]
@stenas Thanks. I think I understand why there was an error here. Since `dom()` does not track page reloading, if any method is called after reloading has started and before the `documentUpdated` event is received, a `DomException` exception with “Could not find node with given id” will be thrown. Because the old id is already out of date, and the new one hasn't been received yet.

I think the `waitForReload()` function should be used wherever the page is expected to reload but as close as possible to code which triggers reloading. I have done so in my scripts. This is better than `sleep()` because sometimes reloading can take longer and random errors may occur.
