### ISSUE TITLE
User Agent error

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#63]
$browser = $browserFactory->createBrowser(['userAgent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko']);

Wil return:
<br />
<b>Fatal error</b>:  Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: sh: 1: Syntax error: &quot;(&quot; unexpected in /opt/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:355
Stack trace:
#0 /opt/vendor/chrome-php/chrome/src/Utils.php(51): HeadlessChromium\Browser\BrowserProcess-&gt;HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process))
#1 /opt/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(390): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator))
#2 /opt/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(125): HeadlessChromium\Browser\BrowserProcess-&gt;waitForStartup(Object(Symfony\Component\Process\Process), 30000000)
#3 /opt/vendor/chrome-php/chrome/src/BrowserFactory.php(80): HeadlessChromium\Browser\BrowserProcess-&gt;start('chromium-browse...', Array)
#4 /var/www/html/domains/x/public_html/x/index.php(57): HeadlessChromium\BrowserFactory-&gt;createBrowser(Array)
#5 {main}
  thrown in <b>/opt/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php</b> on line <b>355</b><br />

**Comment by woodsbox** [comment]
Any idea?
