### ISSUE TITLE
Crashing with Chrome v74 on large HTML files

### ISSUE THREAD

**Issue by jplevene** [chrome-php/headless-chromium-php#92]
I'm getting the error below with larger files.  It loads in well under a second using CURL and takes over a second on my desktop browser to completely render.

The error is caused by the following command:

```
$page->navigate('https://www.web.com/big_file.html')
		 ->waitForNavigation(Page::LOAD, 5000);
```
I've been trying everything all day.  The error first happens above, then any call to page I get a similar error.
This is either a bug in Chrome or this is not compatible with version 74 in someway as I didn't get the problem in v73.

```
**Fatal error:** Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (2sec) in /xxxx/vendor/chrome-php/chrome/src/Utils.php:65 Stack trace: 
#0 /xxxx/vendor/chrome-php/chrome/src/Communication/ResponseReader.php(103): HeadlessChromium\Utils::tryWithTimeout(2000000, Object(Generator)) 
#1 /xxxx/vendor/chrome-php/chrome/src/PageUtils/PageEvaluation.php(69): HeadlessChromium\Communication\ResponseReader->waitForResponse(2000) 
#2 /xxxxx/vendor/chrome-php/chrome/src/PageUtils/PageEvaluation.php(101): HeadlessChromium\PageUtils\PageEvaluation->waitForResponse(NULL) 
#3 /xxxxx/docmaker/merge-pdf-CHROMIUM.php(139): HeadlessChromium\PageUtils\PageEvaluation->getReturnValue() 
#4 /xxx/merge-pdf.php(3): require_once('/xxx/html/m...')
#5 {main} thrown in /xxxx/vendor/chrome-php/chrome/src/Utils.php on line 65
```

```
**Fatal error:** Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (3sec) in /xxxx/vendor/chrome-php/chrome/src/Utils.php:65 Stack trace: 
#0 /xxxx/vendor/chrome-php/chrome/src/Communication/ResponseReader.php(103): HeadlessChromium\Utils::tryWithTimeout(3000000, Object(Generator)) 
#1 /xxxx/vendor/chrome-php/chrome/src/Communication/Connection.php(228): HeadlessChromium\Communication\ResponseReader->waitForResponse(3000) 
#2 /xxxx/vendor/chrome-php/chrome/src/Utils.php(82): HeadlessChromium\Communication\Connection->sendMessageSync(Object(HeadlessChromium\Communication\Message)) 
#3 /xxxx/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(208): HeadlessChromium\Utils::closeAllPage(Object(HeadlessChromium\Communication\Connection)) 
#4 [internal function]: HeadlessChromium\Browser\BrowserProcess->kill() 
#5 {main} thrown in /xxxx/vendor/chrome-php/chrome/src/Utils.php on line 65
```

**Comment by curtiscarlson** [comment]
I get this same bug using the basic example navigating to 'example.com'

**Comment by curtiscarlson** [comment]
OK on 2nd look it is not the same.  My stack trace is 
```

Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (3sec) in C:\GitHub\chrome-php-test\vendor\chrome-php\chrome\src\Utils.php:65
Stack trace:
#0 C:\GitHub\chrome-php-test\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(103): HeadlessChromium\Utils::tryWithTimeout(3000000, Object(Generator))
#1 C:\GitHub\chrome-php-test\vendor\chrome-php\chrome\src\Communication\Session.php(79): HeadlessChromium\Communication\ResponseReader->waitForResponse(3000)
#2 C:\GitHub\chrome-php-test\vendor\chrome-php\chrome\src\Browser.php(149): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#3 C:\GitHub\chrome-php-test\index.php(16): HeadlessChromium\Browser->createPage()
#4 {main}
  thrown in C:\GitHub\chrome-php-test\vendor\chrome-php\chrome\src\Utils.php on line 65
```

Browser.php line 149: 
`$page->getSession()->sendMessageSync(new Message('Page.setLifecycleEventsEnabled', ['enabled' => true]));`

**Comment by jplevene** [comment]
curtiscarlson yours is the same error, it's just you are using puppiteer on Windows

**Comment by jplevene** [comment]
curtiscarlson it is the same, I'm using linux

**Comment by jplevene** [comment]
This is a bug in Chromium (see https://bugs.chromium.org/p/chromium/issues/detail?id=957681) that's causing this.

This package makes it worse as when this problem arises, it drops the session and connection when the exception is called.  The fact is there has been no error, the error raised by Chromium is a bug.

We need an option that the page continues as normal and doesn't drop the websocket connection when errors happen.

**Comment by crislin2046** [comment]
@jplevene you might want to check out this project: [control Headless Chrome from Node.JS and use it like a regular browser](https://github.com/dosycorp/BrowserView)
